### ISSUE TITLE
GladdyEndless to 2.5.1 Classic TBC port?

### ISSUE THREAD

**Issue by Forest-runklebc** [SunstriderEmu/GladdyEndless#3]
Hi SunstriderEmu,

Are you going to port this addon to 2.5.1 Classic TBC that is releasing in a couple weeks?

The current arena frame addons are all very subpar compared to Gladdy.

**Comment by kelno** [comment]
Hey, we're not to handle anything related to Classic TBC at this point, but I'm sure some people will port Gladdy there. 
GladdyEndless is just a fork of Gladdy with some minor changes to improve the experience on the Endless server.
